# Generated by Django 2.1 on 2018-09-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='descs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneaccession', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='genelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneaccession', models.CharField(max_length=15)),
                ('coexpress_gene', models.CharField(max_length=15)),
                ('cor', models.CharField(max_length=100)),
                ('p_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='kegg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneaccession', models.CharField(max_length=15)),
                ('genekegg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneaccession', models.CharField(max_length=15)),
                ('geneontology', models.CharField(max_length=200)),
            ],
        ),
    ]
