# Generated by Django 2.1 on 2018-08-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneaccession', models.CharField(max_length=15)),
                ('coexpress_gene', models.CharField(max_length=15)),
                ('cor', models.CharField(max_length=100)),
                ('p_value', models.CharField(max_length=100)),
            ],
        ),
    ]
