# Generated by Django 2.1 on 2018-08-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='descs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneaccession', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='kegg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneaccession', models.CharField(max_length=15)),
                ('genekegg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneaccession', models.CharField(max_length=15)),
                ('geneontology', models.CharField(max_length=200)),
            ],
        ),
    ]
